name: image_painter
description: A flutter package for drawing over images. Supports color,
  strokeWidth, different paintModes and exporting image.
version: 0.6.3
homepage: https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7
  quickalert: ^1.1.0
